# kubernetes/backstage.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-app
  namespace: backstage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-app
  template:
    metadata:
      labels:
        app: backstage-app
    spec:
      serviceAccountName: backstage-service-account
      containers:
        - name: backstage-app
          image: socrates12345/backstage:1.1.8
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 7007
          envFrom:
            - secretRef:
                name: postgres-secrets
            - secretRef:
                name: backstage-secrets
            - secretRef:
                name: my-backstage-secrets
 
          env:
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_HOST
            value: "localhost"
# Uncomment if health checks are enabled in your app:
# https://backstage.io/docs/plugins/observability#health-checks
#          readinessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
#          livenessProbe:
#            httpGet:
#              port: 7007
#              path: /healthcheck
