---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: workload
  namespace: infra
spec:
  id: previews
  compositionSelector:
    matchLabels:
      provider: civo
      cluster: kubernetes
  parameters:
    nodeSize: g4s.kube.small
    minNodeCount: 1