---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: ClusterClaim
metadata:
  name: previews
  namespace: infra
spec:
  id: previews
  compositionSelector:
    matchLabels:
      provider: provider-civo
      cluster: ck-all
  parameters:
    nodeSize: g4s.kube.small
    minNodeCount: 3  