# kubernetes/postgres-secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: c29jcmF0ZXM=
  POSTGRES_PASSWORD: UXdhc3p4ITIzNDU2
